spring.application.name=ServerConnectivity

# RabbitMQ Connection Settings
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=hornet
spring.rabbitmq.password=hornet

# If using QPID / JMS library:
spring.jms.template.default-destination=task.dispatch.queue

# Tell Spring to run Artemis inside the application (in-vm)
# spring.artemis.mode=embedded

# Memory / Storage persistence (set to false for purely in-memory queues)
# spring.artemis.embedded.persistent=false

# User credentials (optional, default works out-of-the-box in-vm)
# spring.artemis.user=hornet
# spring.artemis.password=hornet

# Automatically create your queues on startup
#spring.jms.template.default-destination=task.dispatch.queue

# Enable TCP connector on port 61616 so external agents can connect
# spring.artemis.embedded.queues=task.dispatch.queue,task.result.queue