spring.application.name=ServerConnectivity

# RabbitMQ Connection Settings
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=hornet
spring.rabbitmq.password=hornet

# If using QPID / JMS library:
spring.jms.template.default-destination=task.dispatch.queue
